apiVersion: v1
kind: Pod
metadata:
  name: my-service
  labels:
    environment: service-app
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    port:
     - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    environment: service-app
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
