apiVersion: v1
kind: Pod
metadata:
  name: nodeport-1
  labels:
    app: nginx
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx
    port:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name:  nodeport-1
spec:
  type: NodePort
  selector:
    app: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
