apiVersion:
kind: pod
metadata:
  name: nodeport
  labels:
    app: nginx
    demo: service
spec:
  containers:
   - name: nginx
     image: nginx
     port:
       - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name:  nodeport
spec:
  type: loadbalancer
  selector:
    app: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
