apiVersion: v1
kind: Pod
metadata:
  name: nodeport
  labels:
    app: nginx
    demo: service
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name:  nodeport
spec:
  type: LoadBalancer
  selector:
    app: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
