apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
     filebeat.config:
      modules:
        usr/share/filebeat/modules.d/*.yml
        reload.enabled: true
     - module: nginx
        access:
         enabled: true
         var.paths: ["/var/log/*nginx-access.log"] # Example for specific NGINX access logs
       error:
         enabled: true
         var.paths: ["/var/log/*nginx-error.log"] # Example for specific
     output.elasticsearch:
       hosts: ["elasticsearch:9200"]  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-nginx
  labels:
    k8s-app: filebeat
  replicas: 2
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
      metadata:
       labels:
        k8s-app: filebeat
      spec:
       containers:
       - name: nginx
         image: nginx
         ports:
         - containerPort: 80
         volumeMounts:
          name: nginx-logs
          mountPath: /var/log/nginx/access.log 
       - name: filebeat-sidecar
         image: docker.elastic.co/beats/filebeat:7.12.0
         volumeMounts:
         -  name: nginx-logs
            mountPath: /var/log/nginx/access.log
         -  name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
       volumes:
       - name: nginx-logs
         emptyDir: {}
       - name: filebeat-config
         configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml



---             

