apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    demo: replica-set
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: replica-set
  template:
    metadata:
      labels:
        app: nginx
        demo: replica-set
    spec:
      containers:
      - name: nginx
        image: nginx
