apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "128Mi"
        cpu: "500m"


---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: hello-pod-1
# spec:
#   # list of containers
#   containers:
#   - name: hello-pod-1
#     image: nginx
#     #here with this line port will not be opened, just for information
#     ports:
#     - containerPort: 80
#     resources:
#       requests:
#         cpu: "100m"
#         memory: "68Mi"
#       limits:
#         cpu: "200m"
#         memory: "128Mi"        