apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-1
spec:
  containers:
  - name: pod-secret-1
    image: nginx 
    ports:
      - containerPort: 80
    envFrom:
     - secretRef:
        name: demo-secret
      